language: rust

install:
- "./ci/install.sh"

script:
- "./ci/build.sh"

deploy:
- provider: script
  script: bash ./ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master

cache: cargo

before_install:
- openssl aes-256-cbc -K $encrypted_27379c917f81_key -iv $encrypted_27379c917f81_iv
  -in deploy_key.enc -out ./deploy_key -d
