// This file is automatically generated from your CSS. Any edits will be overwritten.
export const cell: string;
export const wrong: string;
export const set: string;
export const focus: string;
export const sudoku: string;
export const note: string;
